name: autofix.ci # needed to securely identify the workflow

on:
  pull_request:
  push:
    branches: ["main"]
permissions:
  contents: read
jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 9.7.1

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - run: pnpm install

      - name: Lint
        run: pnpm eslint . --fix
        shell: bash

      - name: Typecheck
        shell: bash
        run: |
          set -eo pipefail
          export NODE_OPTIONS="--max_old_space_size=4096"
          pnpm run typecheck

      - uses: autofix-ci/action@ff86a557419858bb967097bfc916833f5647fa8c
